### ISSUE TITLE
[Nest-cam] Error checking alerts: EAI_AGAIN/Error checking alerts: ETIMEDOUT

### ISSUE THREAD

**Issue by Finch106** [Brandawg93/homebridge-nest-cam#112]
So far this is the only ugly red text I'm seeing in the logs. The googles say "EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error." I haven't changed any of the options. Is this happening because it's checking too often? Would adjusting alertCheckRate help?

**Comment by Brandawg93** [comment]
I don't think checking less often will help. It's usually something with your DNS provider. For some reason, it is unable to translate X.nest.com to an ip address. It could be a firewall issue, or antivirus or something similar.

**Comment by Brandawg93** [comment]
Does this affect plugin functionality?

**Comment by Finch106** [comment]
It doesn't as far as I can tell, I think yesterday Nest in general went down for a little bit. I do have pihole installed so it may need to be whitelisted. Do you have the actual url it's trying to ping?

**Comment by Brandawg93** [comment]
The urls change depending on your location. You should be able to see them, though, in the query logs for pihole. I use pihole as well. One thing that may help you would be [unbound](https://nlnetlabs.nl/projects/unbound/about/). It caches DNS requests to make resolution faster on your entire network.

**Comment by Finch106** [comment]
I'll check that out. I don't see any blocked domains from Nest but I do see a lot of NODATA as the reply.

**Comment by Brandawg93** [comment]
That would definitely do it. Pihole has a simple DNS caching mechanism, but I've changed mine to use unbound, and it has made my network much more stable. I'm going to go ahead and close this since there isn't much else I can do to help, but thanks for the heads up! I went ahead and added this to the [Error Codes Wiki](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Error-Codes). And feel free to continue the conversation after this is closed.
