### ISSUE TITLE
Increased Motion Sensitivity

### ISSUE THREAD

**Issue by brynhewko** [Brandawg93/homebridge-nest-cam#16]
Is there a way to dial up the sensitivity of motion detection on Nest Cameras? I'm finding my autiomation responses slow.

Thanks, and great work on this!

**Comment by Brandawg93** [comment]
The motion sensitivity is based on your settings in the Nest App. If you get a notification from the Nest App, you will more than likely get a notification from the plugin. For instance, if you only have person alerts turned on for a camera, you will not get notifications when a tree moves around. If you change the Nest App setting to include all motion and sound, it will be more sensitive in Homebridge.

**Comment by lunoit** [comment]
I'm also facing a similar issue: the motion alert from Nest is usually 30 seconds or more in advance than the one coming from homekit/homebridge. So there seems to be some sort of delay in the same (motion) trigger..  
Homekit scenario's built on this event are not reliable (in terms of speed) at the moment..

**Comment by Brandawg93** [comment]
There isn't much I can do about the speed without killing the device running homebridge. The Nest app works off push notifications which essentially means a big server that analyses your stream and sends your devices notifications when it finds motion. This is all done really fast since it's done on such a powerful machine, and the best part is your device doesn't have to do any work. I can't tell the Nest server to send the notification to Home kit too, so I have to rely on making the device running homebridge poll every so often for motion. Currently, it's set to poll every 10 seconds because any faster may be too much for the people running small Raspberry Pis.

**Comment by lunoit** [comment]
Thanks for the reply! Maybe a feature request to make the polling interval configurable? I'm not running on a rpi ;-)

**Comment by bhewks** [comment]
I’m running Home bridge on a MacBook Pro on a wired connection and my motion triggers are about 30 seconds delayed
