### ISSUE TITLE
Best device for the plugin

### ISSUE THREAD

**Issue by jvic1234** [Brandawg93/homebridge-nest-cam#163]
Currently using raspberry pie 3+ but using ffmpeg code libx64, the video is really lagged.

using the "copy" the video is still choppy

is raspberry pie 4 the answer or ditch it altogether and use mac mini

what are your thoughts

**Comment by Brandawg93** [comment]
I am using the pi4 and the quality is adequate for my needs. I've never run homebridge on a Mac mini, but several people in the discord server use them and swear by them. I'd suggest asking this in the discord server on the #nest-cam channel. I'm going to close this since it's more of a discussion rather than an issue, but I'd be happy to continue the conversation on discord.
